# Generated by Django 3.1.13 on 2021-10-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='url',
            new_name='cover_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_upload',
            field=models.ImageField(blank=True, default='covers/default.jpg', upload_to='covers/'),
        ),
    ]
